# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yaraft.pb.raftpb_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft_server.proto',
  package='consensus.rpc.pb',
  serialized_pb=_b('\n\x11raft_server.proto\x12\x10\x63onsensus.rpc.pb\x1a\x16yaraft/pb/raftpb.proto\"6\n\x08Response\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.consensus.rpc.pb.StatusCode\"=\n\x07Request\x12#\n\x07message\x18\x01 \x01(\x0b\x32\x12.yaraft.pb.Message\x12\r\n\x05ticks\x18\x02 \x01(\r*<\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cStepLocalMsg\x10\x01\x12\x14\n\x10StepPeerNotFound\x10\x02\x32M\n\x0bRaftService\x12>\n\x05Serve\x12\x19.consensus.rpc.pb.Request\x1a\x1a.consensus.rpc.pb.ResponseB\t\x80\x01\x01\x88\x01\x01\x90\x01\x01')
  ,
  dependencies=[yaraft.pb.raftpb_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='consensus.rpc.pb.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StepLocalMsg', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StepPeerNotFound', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=182,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
OK = 0
StepLocalMsg = 1
StepPeerNotFound = 2



_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='consensus.rpc.pb.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='consensus.rpc.pb.Response.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=117,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='consensus.rpc.pb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='consensus.rpc.pb.Request.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ticks', full_name='consensus.rpc.pb.Request.ticks', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=180,
)

_RESPONSE.fields_by_name['code'].enum_type = _STATUSCODE
_REQUEST.fields_by_name['message'].message_type = yaraft.pb.raftpb_pb2._MESSAGE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.Response)
  ))
_sym_db.RegisterMessage(Response)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.Request)
  ))
_sym_db.RegisterMessage(Request)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001\210\001\001\220\001\001'))

_RAFTSERVICE = _descriptor.ServiceDescriptor(
  name='RaftService',
  full_name='consensus.rpc.pb.RaftService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=244,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='Serve',
    full_name='consensus.rpc.pb.RaftService.Serve',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])

RaftService = service_reflection.GeneratedServiceType('RaftService', (_service.Service,), dict(
  DESCRIPTOR = _RAFTSERVICE,
  __module__ = 'raft_server_pb2'
  ))

RaftService_Stub = service_reflection.GeneratedServiceStubType('RaftService_Stub', (RaftService,), dict(
  DESCRIPTOR = _RAFTSERVICE,
  __module__ = 'raft_server_pb2'
  ))


# @@protoc_insertion_point(module_scope)
