# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yaraft.pb.raftpb_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft_server.proto',
  package='consensus.rpc.pb',
  serialized_pb=_b('\n\x11raft_server.proto\x12\x10\x63onsensus.rpc.pb\x1a\x16yaraft/pb/raftpb.proto\"2\n\x0bStepRequest\x12#\n\x07message\x18\x01 \x02(\x0b\x32\x12.yaraft.pb.Message\":\n\x0cStepResponse\x12*\n\x04\x63ode\x18\x01 \x02(\x0e\x32\x1c.consensus.rpc.pb.StatusCode\"\x1c\n\x0bTickRequest\x12\r\n\x05ticks\x18\x02 \x02(\r\"\x0e\n\x0cTickResponse\"\x0f\n\rStatusRequest\"E\n\x0eStatusResponse\x12\x0e\n\x06leader\x18\x04 \x01(\x04\x12\x11\n\traftIndex\x18\x05 \x01(\x04\x12\x10\n\x08raftTerm\x18\x06 \x01(\x04*<\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cStepLocalMsg\x10\x01\x12\x14\n\x10StepPeerNotFound\x10\x02\x32\xe8\x01\n\x0bRaftService\x12\x45\n\x04Step\x12\x1d.consensus.rpc.pb.StepRequest\x1a\x1e.consensus.rpc.pb.StepResponse\x12\x45\n\x04Tick\x12\x1d.consensus.rpc.pb.TickRequest\x1a\x1e.consensus.rpc.pb.TickResponse\x12K\n\x06Status\x12\x1f.consensus.rpc.pb.StatusRequest\x1a .consensus.rpc.pb.StatusResponseB\t\x80\x01\x01\x88\x01\x01\x90\x01\x01')
  ,
  dependencies=[yaraft.pb.raftpb_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='consensus.rpc.pb.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StepLocalMsg', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StepPeerNotFound', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=309,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
OK = 0
StepLocalMsg = 1
StepPeerNotFound = 2



_STEPREQUEST = _descriptor.Descriptor(
  name='StepRequest',
  full_name='consensus.rpc.pb.StepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='consensus.rpc.pb.StepRequest.message', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=113,
)


_STEPRESPONSE = _descriptor.Descriptor(
  name='StepResponse',
  full_name='consensus.rpc.pb.StepResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='consensus.rpc.pb.StepResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=173,
)


_TICKREQUEST = _descriptor.Descriptor(
  name='TickRequest',
  full_name='consensus.rpc.pb.TickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticks', full_name='consensus.rpc.pb.TickRequest.ticks', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=203,
)


_TICKRESPONSE = _descriptor.Descriptor(
  name='TickResponse',
  full_name='consensus.rpc.pb.TickResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=219,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='consensus.rpc.pb.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=236,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='consensus.rpc.pb.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leader', full_name='consensus.rpc.pb.StatusResponse.leader', index=0,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raftIndex', full_name='consensus.rpc.pb.StatusResponse.raftIndex', index=1,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raftTerm', full_name='consensus.rpc.pb.StatusResponse.raftTerm', index=2,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=307,
)

_STEPREQUEST.fields_by_name['message'].message_type = yaraft.pb.raftpb_pb2._MESSAGE
_STEPRESPONSE.fields_by_name['code'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['StepRequest'] = _STEPREQUEST
DESCRIPTOR.message_types_by_name['StepResponse'] = _STEPRESPONSE
DESCRIPTOR.message_types_by_name['TickRequest'] = _TICKREQUEST
DESCRIPTOR.message_types_by_name['TickResponse'] = _TICKRESPONSE
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE

StepRequest = _reflection.GeneratedProtocolMessageType('StepRequest', (_message.Message,), dict(
  DESCRIPTOR = _STEPREQUEST,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.StepRequest)
  ))
_sym_db.RegisterMessage(StepRequest)

StepResponse = _reflection.GeneratedProtocolMessageType('StepResponse', (_message.Message,), dict(
  DESCRIPTOR = _STEPRESPONSE,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.StepResponse)
  ))
_sym_db.RegisterMessage(StepResponse)

TickRequest = _reflection.GeneratedProtocolMessageType('TickRequest', (_message.Message,), dict(
  DESCRIPTOR = _TICKREQUEST,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.TickRequest)
  ))
_sym_db.RegisterMessage(TickRequest)

TickResponse = _reflection.GeneratedProtocolMessageType('TickResponse', (_message.Message,), dict(
  DESCRIPTOR = _TICKRESPONSE,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.TickResponse)
  ))
_sym_db.RegisterMessage(TickResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQUEST,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.StatusRequest)
  ))
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'raft_server_pb2'
  # @@protoc_insertion_point(class_scope:consensus.rpc.pb.StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001\210\001\001\220\001\001'))

_RAFTSERVICE = _descriptor.ServiceDescriptor(
  name='RaftService',
  full_name='consensus.rpc.pb.RaftService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=372,
  serialized_end=604,
  methods=[
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='consensus.rpc.pb.RaftService.Step',
    index=0,
    containing_service=None,
    input_type=_STEPREQUEST,
    output_type=_STEPRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Tick',
    full_name='consensus.rpc.pb.RaftService.Tick',
    index=1,
    containing_service=None,
    input_type=_TICKREQUEST,
    output_type=_TICKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='consensus.rpc.pb.RaftService.Status',
    index=2,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
])

RaftService = service_reflection.GeneratedServiceType('RaftService', (_service.Service,), dict(
  DESCRIPTOR = _RAFTSERVICE,
  __module__ = 'raft_server_pb2'
  ))

RaftService_Stub = service_reflection.GeneratedServiceStubType('RaftService_Stub', (RaftService,), dict(
  DESCRIPTOR = _RAFTSERVICE,
  __module__ = 'raft_server_pb2'
  ))


# @@protoc_insertion_point(module_scope)
